import {validatePresetRecord,PRESET_MAX_BYTES} from './schema.mjs';
export const CATALOG_SIGNATURE='lyricforge-preset-catalog';
export const CATALOG_SCHEMA_VERSION=1;
export const CATALOG_MAX_BYTES=524288;
function allowedUrl(raw){const u=new URL(raw,globalThis.location?.href||'https://localhost/');if(u.protocol==='https:')return u;if(u.protocol==='http:'&&['localhost','127.0.0.1','::1','[::1]'].includes(u.hostname))return u;throw new Error('Preset catalogs and downloads must use HTTPS outside localhost.');}
async function limitedText(response,maxBytes,label){if(!response?.ok)throw new Error(`${label} request failed (${response?.status||'network'}).`);const len=Number(response.headers?.get?.('content-length'));if(Number.isFinite(len)&&len>maxBytes)throw new Error(`${label} is too large.`);const text=await response.text();if(new TextEncoder().encode(text).byteLength>maxBytes)throw new Error(`${label} is too large.`);return text;}
function clean(v,n=256){return String(v??'').slice(0,n)}
export async function fetchPresetCatalog(url='./presets/catalog.json',{signal,fetchImpl=fetch}={}){const catalogUrl=allowedUrl(url);const text=await limitedText(await fetchImpl(catalogUrl.href,{signal,cache:'no-store'}),CATALOG_MAX_BYTES,'Preset catalog');let data;try{data=JSON.parse(text)}catch{throw new Error('Preset catalog contains invalid JSON.')}if(data?.signature!==CATALOG_SIGNATURE||Number(data?.schemaVersion)!==CATALOG_SCHEMA_VERSION||!Array.isArray(data?.entries))throw new Error('Preset catalog format is invalid.');const entries=data.entries.slice(0,1000).map(e=>{const downloadUrl=allowedUrl(new URL(e.downloadUrl,catalogUrl).href).href;let thumbnailUrl=null;if(e.thumbnailUrl){try{thumbnailUrl=allowedUrl(new URL(e.thumbnailUrl,catalogUrl).href).href}catch{thumbnailUrl=null}}return{id:clean(e.id,96),name:clean(e.name,120),author:clean(e.author,120),category:clean(e.category,80,'Other'),tags:Array.isArray(e.tags)?e.tags.slice(0,20).map(v=>clean(v,40)):[],version:clean(e.version,32,'1.0.0'),minAppVersion:clean(e.minAppVersion,32,'0.3.7'),downloadUrl,thumbnailUrl};}).filter(e=>e.id&&e.name&&e.downloadUrl);return{signature:CATALOG_SIGNATURE,schemaVersion:CATALOG_SCHEMA_VERSION,updatedAt:clean(data.updatedAt,64),entries};}
export function searchPresetCatalog(entries,{query='',category=''}={}){const q=String(query).trim().toLowerCase(),cat=String(category).trim().toLowerCase();return (entries||[]).filter(e=>(!cat||cat==='all'||String(e.category).toLowerCase()===cat)&&(!q||[e.name,e.author,...(e.tags||[])].some(v=>String(v).toLowerCase().includes(q))));}
export async function downloadPreset(entry,{signal,fetchImpl=fetch}={}){if(!entry?.downloadUrl)throw new Error('Preset download URL is missing.');const url=allowedUrl(entry.downloadUrl);const text=await limitedText(await fetchImpl(url.href,{signal,cache:'no-store'}),PRESET_MAX_BYTES,'Preset file');let record;try{record=validatePresetRecord(text,{maxBytes:PRESET_MAX_BYTES})}catch(e){if(e instanceof SyntaxError)throw new Error('Preset file contains invalid JSON.');throw e;}if(record.id!==entry.id||record.version!==entry.version)throw new Error('Downloaded preset does not match catalog id/version metadata.');return record;}
